### ISSUE TITLE
Can we add call-outs to this document?

### ISSUE THREAD

**Issue by crystalrubik** [cdig/cd-map#2]
Couldn't get callouts to work and came here to check on an example and noticed it's not mentioned here. Should it be here? I learned from a Trican acid page it's call-out. ;)

Thanks!

**Comment by ivanreese** [comment]
Notes on call outs should be added to the docs (or wiki) on cd-module. cd-map is used by (and will in the future be used by) dozens and dozens of different things, so this isn't a good place to document them all. That said, it might be good to add a wiki page here that points to docs for the different things that use cd-map, though.
